version: '3.8'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./backend/mongo/dev-mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./backend/mongo/data:/data/db
  redis:
    image: redis
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./backend/redis/data:/data
    deploy:
      replicas: 2
  app:
    image: leoalho/wesail
    environment: 
      - REDIS_URI=redis://redis:6379
      - MONGODB_URI=mongodb://the_username:the_password@mongo:27017/the_database?directConnection=true
      - NODE_ENV=production
      - SECRET=secret
    depends_on:
      - redis
      - mongo
    deploy:
      replicas: 2
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginxlocal.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 3000:80
    depends_on:
      - app
    deploy:
      replicas: 2
  shepherd:
    image: mazzolino/shepherd
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
        - node.role == manager