version: '3.8'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./Wesailbackend/mongo/dev-mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./Wesailbackend/mongo/data:/data/db
  redis:
    image: redis
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./Wesailbackend/redis/data:/data
  app:
    image: wesailapp
    build: .
    ports:
      - 3001:3001
    environment: 
      - REDIS_URI=redis://redis:6379
      - MONGODB_URI=mongodb://the_username:the_password@mongo:27017/the_database
      - NODE_ENV=production
      - SECRET=secret
