version: '3.8'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./backend/mongo/dev-mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./backend/mongo/data:/data/db
  redis:
    image: redis
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./backend/redis/data:/data
  app:
    image: wesailapp
    build: .
    environment: 
      - url = http://localhost
      - REDIS_URI=redis://redis:6379
      - MONGODB_URI=mongodb://the_username:the_password@mongo:27017/the_database?directConnection=true
      - NODE_ENV=production
      - SECRET=secret
    depends_on:
      - redis
      - mongo
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    container_name: reverse-proxy
    depends_on:
      - app