version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./mongo/dev-mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./mongo/data:/data/db
  server:
    image: wesailbackend
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 3001:3001
    environment: 
      - MONGODB_URI=mongodb://the_username:the_password@mongo:27017/the_database
  debug-helper:
    image: busybox