apiVersion: apps/v1
kind: Deployment
metadata:
  name: wesail-deployment
  labels:
    app: wesail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wesail
  template:
    metadata:
      labels:
        app: wesail
    spec:
      containers:
      - name: wesail
        image: mongo:5.0
        ports:
        - containerPort: 3001
        env:
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-url
        - name: NODE_ENV
          value: production
        - name: SECRET
          value: secret
        - name: REDIS_URI
          value: redis://redis:6379
---
apiVersion: v1
kind: Service
metadata:
  name: wesail-service
spec:
  type: NodePort
  selector:
    app: wesail
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30100