name: CI pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
jobs:
  backend:
    name: backend
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Redis Server in GitHub Actions
        uses: supercharge/redis-github-action@1.4.0
      - name: npm install 
        run: npm install  
      - name: lint        
        run: npm run lint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
  frontend:
    name: frontend
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: npm install 
        run: npm install  
      - name: lint        
        run: npm run lint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
  publish-docker-hub:
    name: Publish image to Docker Hub
    runs-on: ubuntu-latest
    needs: [frontend, backend]
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      if: github.event_name == 'push' && contains(join(toJson(github.event.commits.*.message), ' '), '#skip') != true
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push api
      if: github.event_name == 'push' && contains(join(toJson(github.event.commits.*.message), ' '), '#skip') != true
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.api
        push: true
        tags: leoalho/wesailApi:latest
    - name: Build and push server
      if: github.event_name == 'push' && contains(join(toJson(github.event.commits.*.message), ' '), '#skip') != true
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: leoalho/wesailServer:latest
  tag_release:
    needs: [frontend, backend]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Bump version and push tag
        if: github.event_name == 'push' && contains(join(toJson(github.event.commits.*.message), ' '), '#skip') != true
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: "patch"
          WITH_V: true