name: CI pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
jobs:
  backend:
    runs_on: ubuntu-20.04
    defaults:
      run:
        working-directory: WeSailBackend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: npm install 
        run: npm install  
      - name: lint        
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
  frontend:
    runs_on: ubuntu-20.04
    defaults:
      run:
        working-directory: WeSailFrontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: npm install 
        run: npm install  
      - name: lint        
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
  tag_release:
    needs: [frontend, backend]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Bump version and push tag
        if: github.event_name == 'push' && contains(join(toJson(github.event.commits.*.message), ' '), '#skip') != true
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: "patch"
          WITH_V: true